---
date: last-modified
bibliography: bio.bib
csl: harvard-cite-them-right.csl
title: The Pythoneers' Group Project
execute:
  echo: false
  freeze: true
format:
  html:
    code-copy: true
    code-link: true
    toc: true
    toc-title: On this page
    toc-depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    mainfont: Spectral
    sansfont: "Roboto Flex"
    monofont: "Liberation Mono"
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
    toc: false
    number-sections: false
    colorlinks: true
    highlight-style: github
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.15.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

## Declaration of Authorship {.unnumbered .unlisted}

We, The Pythoneers, pledge our honour that the work presented in this assessment is our own. Where information has been derived from other sources, we confirm that this has been indicated in the work. Where a Large Language Model such as ChatGPT has been used we confirm that we have made its contribution to the final submission clear.

Date: 16 December 2025 (Tuesday)

| Names          | Student Numbers | Contact Email                |
|----------------|-----------------|------------------------------|
| Owen Hughes    | 25197128        | owen.hughes.25\@ucl.ac.uk    |
| Benjamin Tee   | 25049107        | benjamin.tee.25\@ucl.ac.uk   |
| Alice Southall | 25120600        | alice.southall.25\@ucl.ac.uk |
| Bosco Choi     | 22040212        | bosco.choi.22\@ucl.ac.uk     |
| Tong, C.Y      | 25244321        | c.tong.25\@ucl.ac.uk         |

## Priorities for Feedback

Are there any areas on which you would appreciate more detailed feedback if we're able to offer it?

{{< pagebreak >}}

# Briefing on Airbnb Growth Trends & Policy Implications

### **1. Is Airbnb ‘out of control’ in London?**

Opposition critics have suggested that the growth and spread of Airbnbs in London has accelerated, with professional landlords rapidly accumulating properties and flouting rental restrictions to make a profit. The increase of short-term lets and its potential to damage the housing supply in London is a concern that the Mayor's office had raised [previously](https://www.london.gov.uk/mayor-demands-licencing-scheme-prevent-short-term-lets-damaging-housing-supply), and is one of the reasons that London's 90-day limit was introduced. Indeed, the Mayor called for a registration system to be put in place in [2019](www.london.gov.uk/press-releases/mayoral/registration-system-for-short-term-letting-law). This chapter provides a systematic analysis of the situation. 

#### What is the growth trend in Airbnb listings across London?

Since 2021 London has seen a dramatic increase in the amount of Airbnb listings rising from **69,298** to **86,463** in 2025, a **25% increase**. The majority of these listings arose between 2022 and 2023 with the most evident concentration of new listings appearing in central London boroughs. Specifically, the boroughs of Westminster, Camden, Southwark, Lambeth, and Kensington and Chelsea saw the highest increases in listings, Westminster alone adding nearly **3,000** listings constituting a **39% increase** in available Airbnbs within the borough.

#### How does this compare to changes in the overall housing stock?

In comparison to the **25% increase** of Airbnb listings, London housing stock increases lag significantly behind. Between 2020 and 2024, London grew from **3.68M to 3.81M** properties constituting a relatively mere **3.7% increase** in housing stock. Unsurprisingly, when comparing the ratio of listings increases and housing stock increases at the borough level, central London boroughs display more accelerated rates of listings increases compared to housing stock increases than peripheral boroughs. In particular Kensington and Chelsea saw **5 times** more new Airbnb listings than new housing stock between 2020 and 2024.

Across all London boroughs in 2025, the average amount of listings as a percent total housing stock is **1.86%**, though eleven boroughs exceed this average. All eleven boroughs are located in central London with Westminster and Kensington and Chelsea having close to **6%** of their total housing stock listed as an Airbnb. The combination of this accelerated and geographically concentrated growth in listings and a tightening housing market suggests that Airbnb can be considered out of control, particularly within central London boroughs.

#### How many listings potentially breach the current 90-day limit for rentals?

Since 2017, London planning rules state that entire homes let on platforms such as Airbnb should not be used for short-term letting for more than 90 nights per calendar year, without planning permission obtained. This prevents permanent housing from being converted into de facto holiday accommodation.

Considering just *Entire Home/Apt* listings (67% of all listings), **12,081 or 21%** of listings exceed the 90 day limit, and assuming multiple listings of the same property this evaluation should be considered conservative. Additonally, it is once again central London Boroughs that display the highest rates of excessive use with eight central boroughs having over **20%** of listings let for more than 90 days.

### **2. How many professional landlords are there?**

Relevent literature investigating how Airbnb listings affect local rent and property value (Todd et al., Cox and Slee) suggest that a commercial or professional landlord can be a company or individual that owns and operates 2 or more *Entire Home/Apt* listings. With this, chapters two and three undertake analysis of just *Entire Homes/Apt* listings with additional emphases on properties that violate the previously mentioned 90 day maximum let limit and the viability of Airbnb as a primary source of income.

#### Professional landlords and economic viability

As of 2025, London is home to **32,704 unique hosts** of *Entire Home/Apt* listings, of which **27,108 (85%)** are landlords to a single a property. This means, assuming professional landlords are hosts with two or more properties, that there are **4,966 (15%) professional hosts** in London. After calculating a median yearly income range among multi-listing hosts for standard lets (any listings let for fewer than 90 days) and frequent lets (any listing let for more than 90 days) of **£5,600 - £30,300** and combing this with the median income of London (provided by *London Data Store*) of **£34,100**, an analysis of financial viability of becoming a professional host is possible. Using the more conservative yearly income of £5,600, **owning seven properties** becomes the threshold to make more than the London median income. In contrast, **owning just two properties** is sufficient to make close to double the median income of London when letting for more than 90 days. Given the range of income, one can definitively suggest that owning between just **2 and 7** listings is sufficient to make Airbnb a source of primary income.

Despite the clear results of the above analysis, significant assumptions were made in it's calculation. The estimated revenue of each listing was taken from *Inside Airbnb* though a significant amount of listings contained a null value for its yearly estimated revenue. Thus, the yearly revenue range above (£5,600 - £30,300) was calculated using the mean revenue of Airbnbs owned by multi-listing hosts with a valid 365 day revenue estimate. Additionally, a similar revenue range was calculated for single-listing properties of **£4,858 - £24,000**. These lower values are to be expected, though even with only a single property let for over 90 days, one, on average, makes **70%** of the London median income, further displaying the economic benefit of circumventing London's 90 day let limit.

### **3. How many properties would be affected by the opposition’s proposal?**

#### Opposition proposal and effects if enacted

The opposition has suggested that all professional landlords must register their properties with their council and subsequently face increased council tax. However, this raises concerns as council tax is currently based on the market price of a property in 1991; which suggests that raising council tax for some would result in increased council tax for all.

Despite uncertainty about the ability to target specific properties with increased council tax, assuming the opposition's proposal is enacted a number of conclusions can be made. First, assuming that all properties are only listed once, **30,154** properties owned by professional landlords would be subject to increased council tax. Second, This makes up **53% of all *Entire Home/Apt listings***, meaning that over half of these listings are owned by only 15% of hosts. Lastly, inspecting the amount of properties that breach the 90 day let limit again displays popularity of this loophole. Of all *Entire Home/Apt* listings, **7%** are owned by single-list hosts and let for more than 90 days while **14%** are owned by professional hosts and let for more than 90 days. Considering that professional host take advantage of over-letting **twice as often** as single-list hosts and own a disproportionate amount of Airbnb listings, the next two chapters will discuss how to apply the opposition's desire to target professional hosts in a way that does not raise tax for all.

### **4. What are the likely pros and cons of the opposition’s proposal (for the Mayor, for residents, and for the city)?**

### **5. Can the story be reframed as a positive one about social mobility or housing opportunity?**

{{< include _questions.qmd >}}

## References