---
title: "Owen_Week7_Code"
format: html
editor: visual
---

# Week 7 Code

## Questions to Answer

**1. What is the share of Airbnbs in London that are entire homes or apartments?**

-   Use pandas to group listings by type

-   Create a plot showing percent and totals

**2. How many professional landlords are there in London?**

-   What is the difference between a professional landlord and a commercial landlord?

    -   Does this difference matter for out analysis

-   Start by analyzing anyone/organization that owns more than 2 entire home/apt Airbnbs

    -   group Airbnbs by host and count listings per host

-   Income from these properties vs. median income in London

------------------------------------------------------------------------

**Data setup**

Load the pandas package and data

```{r}
#library(reticulate)
#py_install('pandas')
#py_install('matplotlib')
```

```{python}
import pandas as pd
```

```{python}
df = pd.read_csv("C:/Users/Owen Hughes/Desktop/CASA/UCL_Work/CASA_FSDS_Project/Data/clean/20250615-London-listings.csv/20250615-London-listings.csv")

df.head(4)
```

------------------------------------------------------------------------

**1. What is the share of Airbnbs in London that are entire homes or apartments?**

-   The most useful column for this analysis is room_type as groups and counts can be made to determine the proportion of Airbnbs that are entire houses or flats. Additionally, the length of the data set will used to calculate said proportion.

```{python}
# attain length of data set for calculation of proportion
df_length = len(df)
print(df_length)
```

```{python}
# run a for loop to create a new data set with only entire homes apartments 
# take the length of this

print(df["room_type"].unique())

entire_homes = []
for i, r in df.iterrows():
  if r["room_type"] == "Entire home/apt":
    entire_homes.append(r)
  
entire_homes_df = pd.DataFrame(entire_homes) # Ensure data is still a pandas df

eh_length = len(entire_homes_df)
print(eh_length)
```

```{python}
# Find the proportion of Airbnbs that are entire homes
print(f'Rounghly {round((eh_length/df_length)*100)}% of Airbnbs in London are entire homes or flats.')
```

From this simple analysis alone, we see that Airbnb certainly has a tendency to attract entire homes and apartments as its primary form of short term rental housing. Whether this is purposeful from the company cannot be determined from this analysis, though 57,168 entire homes and apartments that could be used for full time resident housing will certainly have an effect on the housing market.

Now I want to display in a bar chart and a pie chart the total counts of each room type and their proportions.

```{python}
import matplotlib.pyplot as plt
```

```{python}

room_types = df["room_type"].value_counts()

# The next lines come from Geeks for Geeks
# Function to add value labels on top of bars
def add_labels(x, y):
    for i in range(len(x)):
        plt.text(i, y[i], y[i], ha='center', 
                 bbox=dict(facecolor='#ABD7EB', alpha=0.8))

x = ["Entire home/apt", "Private room", "Shared room", "Hotel room"]
y = [57168, 28367, 180, 101]

plt.figure(figsize=(10, 5))
plt.bar(x,y, color = "salmon")
add_labels(x,y)
# Adding title and labels
plt.title("Airbnb Types in London")
plt.xlabel("Room Types")
plt.ylabel("Count")

# Display the chart
plt.show()
```

```{python}

room_counts = df["room_type"].value_counts()

# Plot
plt.figure(figsize=(6, 6))
plt.pie(room_counts, labels=room_counts.index, autopct="%1.1f%%", startangle=90, colors=["#ABD7EB", "#F4A261", "#E76F51", "#2A9D8F"])
plt.title("Proportion of Room Types in London Listings")
plt.axis("equal")  # Ensures pie is a circle
plt.show()

```

--------------------------------------------------------------------------------------------------------------------

**What is a Professional Landlord? What is a Commercial Landlord?**

We know from the paper by James Todd et al. that "a unit increase in the number of Airbnb properties listings yielded a singnificant increase on the house price by £11.59 per square meter" (215). Additionally, both the paper by Todd et al. and Cox and Slee recgonize that "multi listing hosts" are significant drivers of this increase in rent and Airbnbs profit in London (Cox and Slee, 2).

Our initial starting point was to use 5 properties as the threshold for professional and commercial landlords, though both the papers above suggest that a more accurate cutoff may be just 2 entire home/apt properties. Though this is still an inherently arbitrary quantification, maintaining status quo from other relevant studies is useful for us.

Additionally, a significant assumption for using these papers as the basis for this section of analysis is that we treat professional and commercial landlords in the same way in the analysis. The overall argument from both papers suggests that multi listing hosts are significantly responsible fro rising rent prices and Airbnb profit. In this sense, the only difference between a professional and commercial landlord is the quantity of properties listed and whether it is an individual or company that owns said properties. For the sake of this analysis, no differentiation will be made between the two.

Lastly, Inside Airbnb also provides basic information regarding average income of Airbnbs in London in two categories: All and Recent/Frequently Booked. After the analysis to determine how many professional landlords there are, and assuming all their properties make the average income, an analysis of each professional/commercial landlord's income will follow.

Cox, Murray, and Tom Slee. “How Airbnb’s Data Hid the Facts in New York City.” *Inside Airbnb*, 10 Feb. 2016, insideairbnb.com/reports/how-airbnbs-data-hid-the-facts-in-new-york-city.pdf.

Todd, James, et al. “Assessing the impacts of airbnb listings on London house prices.” *Environment and Planning B: Urban Analytics and City Science*, vol. 49, no. 1, 22 Mar. 2021, pp. 206–222, https://doi.org/10.1177/23998083211001836.

**Group landlords by listings to find the professional/commercial hosts**

```{python}
# As suggeseted in the papers, filter only the entire home/apts

entire_homes_df.head(4)
```
